sudo: false
os:
  - linux

dist:
  - trusty

matrix:
  include:
    - language: nix
      before_script:
        - nix-env -i carnix cargo
        - cargo build --all
        - carnix --standalone --src . --output build.nix Cargo.lock
      script:
        - nix-build ./build.nix -A imag_0_6_0
    - language: rust
      rust: 1.21.0
      script:
        - cargo build --all --all-features --verbose -j 1
        - cargo test --all --all-features --verbose -j 1
    - language: rust
      rust: 1.22.1
      script:
        - cargo build --all --all-features --verbose -j 1
        - cargo test --all --all-features --verbose -j 1
    - language: rust
      rust: 1.23.0
      script:
        - cargo build --all --all-features --verbose -j 1
        - cargo test --all --all-features --verbose -j 1
    - language: rust
      rust: stable
      script:
        - cargo build --all --all-features --verbose -j 1
        - cargo test --all --all-features --verbose -j 1
    - language: rust
      rust: beta
      script:
        - cargo build --all --all-features --verbose -j 1
        - cargo test --all --all-features --verbose -j 1
    - language: rust
      rust: nightly
      allowed_failure: nightly
      script:
        - cargo build --all --all-features --verbose -j 1
        - cargo test --all --all-features --verbose -j 1

cache:
  cargo: true

addons:
  apt:
    packages:
    - libdbus-1-dev
    - pkg-config

notifications:
  email:
    on_success: never
  irc:
    channels:
      - chat.freenode.net#imag
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"

