# This is a example configuration file for the imag suite.
# It is written in TOML

# The alias section
#
# In this section one can define aliases for imag subcommands.
#
# E.G: An alias `store = [ "s", "st" ]` allows the user to call `imag s` or
# `imag st` for calling `imag store`.
#
# The aliases have to be either a single string or an array of strings, where no
# string contains whitespace (thus, aliasing a "store-create" call to "sc" for
# example is not supported).
#
[imag.aliases]
store = [ "s", "st" ]

[imag.logging]
level = "debug"
destinations = [ "-" ]

# Valid variables for logging:
#  * "level"
#  * "module_path"
#  * "file"
#  * "line"
#  * "target"
#  * "message"
#
# Valid functions to be applied:
#  * "black"
#  * "blue"
#  * "cyan"
#  * "green"
#  * "purple"
#  * "red"
#  * "white"
#  * "yellow"

[imag.logging.format]
trace = "[imag][{{red level}}][{{module_path}}]: {{message}}"
debug = "[imag][{{cyan level}}][{{yellow target}}]: {{message}}"
info  = "[imag]: {{message}}"
warn  = "[imag][{{bold level}}]: {{yellow message}}"
error = "[imag][{{red level}}]: {{red message}}"

#
# Configuration options for the user interface
#
[ui]

#
# Configuration options for the commandline user interface
#
[ui.cli]

# History file path for readline. Will be created by imag if it does not exist.
readline_history_file = "/tmp/readline.history"

# Number of lines to safe in the history file
readline_history_size = 100

# Ignore duplicated lines
readline_history_ignore_dups = true

# Tell if lines which begin with a space character are saved or not in the
# history list.
readline_history_ignore_space = true

# The prompt string to use
readline_prompt = ">> "

[store]

# Set to false if you do not want imag to create the directory where the store
# lives implicitely
implicit-create = false

[diary]
default_diary = "default"

[diary.diaries.default]
timed = "minutely"

[bookmark]
default_collection = "default"

