[package]
name = "libimaglink"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
itertools = "0.4.7"
log = "0.3.4"
toml = "0.1.27"
url = "0.5.5"

[dependencies.libimagstore]
path = "../libimagstore"

