[package]
name = "libimaglink"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
log = "0.3.4"
toml = "0.1.27"
semver = "0.2"
url = "0.5.5"

[dependencies.libimagstore]
path = "../libimagstore"

