[package]
name = "libimagtodo"
version = "0.1.0"
authors = ["mario <mario-krehl@gmx.de>"]

[dependencies]
task-hookrs = { git = "https://github.com/matthiasbeyer/task-hookrs.git" }

[dependencies.libimagstore]
path = "../libimagstore"

