[package]
name = "libimagtodo"
version = "0.2.0"
authors = ["mario <mario-krehl@gmx.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[profile.dev]
codegen-units = 2

[dependencies]
semver = "0.2"
task-hookrs = "0.2.2"
uuid = "0.3"
toml = "0.2.*"
log = "0.3"
serde_json = "0.8"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

