[package]
name = "imag-annotate"
version = "0.5.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-annotate command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[badges]
travis-ci                         = { repository = "matthiasbeyer/imag" }
is-it-maintained-issue-resolution = { repository = "matthiasbeyer/imag" }
is-it-maintained-open-issues      = { repository = "matthiasbeyer/imag" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
clap = ">=2.17"
log = "0.3"
version = "2.0.1"
url = "1.2"
toml = "0.4"
toml-query = "0.4"

libimagstore     = { version = "0.5.0", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.5.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.5.0", path = "../../../lib/core/libimagerror" }
libimagentryannotation = { version = "0.5.0", path = "../../../lib/entry/libimagentryannotation" }
libimagentryedit = { version = "0.5.0", path = "../../../lib/entry/libimagentryedit" }
libimagutil      = { version = "0.5.0", path = "../../../lib/etc/libimagutil" }

