[package]
name = "libimagnotes"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
semver = "0.2"
log = "0.3"
toml = "0.2.*"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagentrytag]
path = "../libimagentrytag"

