[package]
name = "libimagentrylist"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
clap = "2.1.1"
log = "0.3.5"
toml = "0.1.25"

[dependencies.libimagstore]
path = "../libimagstore"

