[package]
name = "imag-link"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
semver = "0.2.1"
clap = "2.1.1"
log = "0.3"
version = "2.0.1"
toml = "0.1.25"
url = "1.1"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagentrylink]
path = "../libimagentrylink"

[dependencies.libimagerror]
path = "../libimagerror"

