[store]
implicit-create = true
store-unload-hook-aspects  = []
pre-create-hook-aspects    = []
post-create-hook-aspects   = []
pre-move-hook-aspects      = []
post-move-hook-aspects     = []
pre-retrieve-hook-aspects  = []
post-retrieve-hook-aspects = []
pre-update-hook-aspects    = []
post-update-hook-aspects   = []
pre-delete-hook-aspects    = []
post-delete-hook-aspects   = []

[store.aspects.debug]
parallel = false

[store.aspects.vcs]
parallel = false

[store.hooks.stdhook_debug]
aspect = "vcs"

[store.hooks.stdhook_git_update]
aspect = "vcs"
enabled = false

[store.hooks.stdhook_git_update.commit]
enabled = false

[store.hooks.stdhook_git_delete]
aspect = "vcs"
enabled = false

[store.hooks.stdhook_git_delete.commit]
enabled = false

[store.hooks.stdhook_git_storeunload]
aspect = "vcs"
enabled = false

[store.hooks.stdhook_git_storeunload.commit]
enabled = false
