[package]
name = "libimagstore"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
fs2 = "0.2"
glob = "0.2.11"
lazy_static = "0.1.15"
log = "0.3"
regex = "0.1"
semver = "0.2"
toml = "0.2.*"
version = "2.0.1"
crossbeam = "0.2.8"
walkdir = "0.1.5"

libimagerror = "0.2.0"
libimagutil  = "0.2.0"

[dev-dependencies]
tempdir = "0.3.4"
env_logger = "0.3"

[features]
default = []
verify  = []

