[package]
name = "imag-ref"
version = "0.4.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-ref command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
semver = "0.5.1"
clap = ">=2.17"
log = "0.3"
version = "2.0.1"

libimagstore       = { version = "0.4.0", path = "../../../lib/core/libimagstore" }
libimagrt          = { version = "0.4.0", path = "../../../lib/core/libimagrt" }
libimagerror       = { version = "0.4.0", path = "../../../lib/core/libimagerror" }
libimagref         = { version = "0.4.0", path = "../../../lib/entry/libimagentryref" }
libimagentrylist   = { version = "0.4.0", path = "../../../lib/entry/libimagentrylist" }
libimaginteraction = { version = "0.4.0", path = "../../../lib/etc/libimaginteraction" }
libimagutil        = { version = "0.4.0", path = "../../../lib/etc/libimagutil" }

