[package]
name = "libimagstorestdhook"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
toml = "0.1.25"
log = "0.3"
fs2 = "0.2.3"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagentrylink]
path = "../libimagentrylink"

[dependencies.libimagutil]
path = "../libimagutil"

