[package]
name = "imag-notes"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
semver = "0.2.1"
clap = "2.1.1"
log = "0.3.5"
version = "2.0.1"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagnotes]
path = "../libimagnotes"

[dependencies.libimagentrytag]
path = "../libimagentrytag"

[dependencies.libimagutil]
path = "../libimagutil"

