[package]
name = "imag-grep"
version = "0.5.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-grep command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = ">=2.17"
version = "2.0.1"
regex = "0.2"

libimagstore     = { version = "0.5.0", path = "../../../lib/core/libimagstore" }
libimagrt        = { version = "0.5.0", path = "../../../lib/core/libimagrt" }
libimagerror     = { version = "0.5.0", path = "../../../lib/core/libimagerror" }

