[package]
name = "imag-documentation"
version = "0.3.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Documentation crate of the imag distribution. Does not contain functionality"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]

libimagbookmark = "0.3.0"
libimagcounter = "0.3.0"
libimagdiary = "0.3.0"
libimagentryfilter = "0.3.0"
libimagentrylink = "0.3.0"
libimagentrylist = "0.3.0"
libimagentrymarkdown = "0.3.0"
libimagentrytag = "0.3.0"
libimagentryview = "0.3.0"
libimagerror = "0.3.0"
libimaginteraction = "0.3.0"
libimagnotes = "0.3.0"
libimagref = "0.3.0"
libimagrt = "0.3.0"
libimagstore = "0.3.0"
libimagtimeui = "0.3.0"
libimagutil = "0.3.0"
