[package]
name = "imag-documentation"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Documentation crate of the imag distribution. Does not contain functionality"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]

libimagbookmark      = "0.2.0"
libimagcounter       = "0.2.0"
libimagdiary         = "0.2.0"
libimagentryfilter   = "0.2.0"
libimagentrylink     = "0.2.0"
libimagentrylist     = "0.2.0"
libimagentrymarkdown = "0.2.0"
libimagentrytag      = "0.2.0"
libimagentryview     = "0.2.0"
libimagerror         = "0.2.0"
libimaginteraction   = "0.2.0"
libimagnotes         = "0.2.0"
libimagref           = "0.2.0"
libimagrt            = "0.2.0"
libimagstore         = "0.2.0"
libimagstorestdhook  = "0.2.0"
libimagtimeui        = "0.2.0"
libimagutil          = "0.2.0"

