[package]
name = "imag-contact"
version = "0.5.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-contact command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../../../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
clap = ">=2.17"
log = "0.3"
version = "2.0.1"
toml = "0.4"
toml-query = "^0.3.1"
handlebars = "0.29"
vobject     = { git = 'https://github.com/matthiasbeyer/rust-vobject', branch = "next" }
walkdir = "1"
uuid = { version = "0.5", features = ["v4"] }

libimagrt      = { version = "0.5.0", path = "../../../lib/core/libimagrt" }
libimagstore   = { version = "0.5.0", path = "../../../lib/core/libimagstore" }
libimagerror   = { version = "0.5.0", path = "../../../lib/core/libimagerror" }
libimagcontact = { version = "0.5.0", path = "../../../lib/domain/libimagcontact" }
libimagutil    = { version = "0.5.0", path = "../../../lib/etc/libimagutil" }
libimagentryref = { version = "0.5.0", path = "../../../lib/entry/libimagentryref" }
libimagentryedit = { version = "0.5.0", path = "../../../lib/entry/libimagentryedit" }
libimaginteraction    = { version = "0.5.0", path = "../../../lib/etc/libimaginteraction" }

