[package]
name = "libimagdiary"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
chrono = "0.2"
log = "0.3.5"
semver = "0.2"
toml = "0.2.*"
regex = "0.1"
lazy_static = "0.2"
itertools = "0.4"

libimagentryedit = "0.2.0"
libimagentryview = "0.2.0"
libimagerror     = "0.2.0"
libimagrt        = "0.2.0"
libimagstore     = "0.2.0"
libimagutil      = "0.2.0"

