[package]
name = "libimagtag"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
log = "0.3.5"
regex = "0.1.47"
toml = "0.1.25"

[dependencies.libimagstore]
path = "../libimagstore"

